apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-app
  namespace: argocd
spec: 
  destination: 
    namespace: helm-app   #namespace donde se ejecutara la app
    server: "https://kubernetes.default.svc"    #cluster donde se va a ejecutar
  project: default
  source: 
    path: helm-guestbook  #nombre de la carpeta en git
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"  #url de la repo de git
    targetRevision: master   #rama de git
    helm:
     releaseName: helm-app-version-2   #nombre del release de helm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true   #si no existe el namespace, argocd lo va a crear