apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-app-serret
  namespace: argocd
spec:
  destination:
    namespace: my-app-serret
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: my-deployment
    repoURL: "https://github.com/luisserret/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true