apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/luisserret/argocd-example-apps.git
  password: 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
  username: argocd